#!/bin/bash

  
# install the Datadog agent
DD_AGENT_MAJOR_VERSION=7 DD_API_KEY=xxx DD_SITE="datadoghq.eu" bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/datadog-agent/master/cmd/agent/install_script.sh)"
chown dd-agent /etc/datadog-agent/auth

 # Enable logs, process and network collection
sudo -u dd-agent echo "logs_enabled: true
process_config:
  enabled: \"true\"
tags:
    - "env:xxx"" >>/etc/datadog-agent/datadog.yaml

sudo -u dd-agent cp /etc/datadog-agent/system-probe.yaml.example /etc/datadog-agent/system-probe.yaml

  # Enable network collection
sudo -u dd-agent  echo "system_probe_config:
  enabled: true" >> /etc/datadog-agent/system-probe.yaml

#Enable Zookeeper

sudo cp /etc/datadog-agent/conf.d/zk.d/conf.yaml.example /etc/datadog-agent/conf.d/zk.d/conf.yaml

#Enable logs for ZK
sudo echo "logs:
  - type: file
    path: /var/log/zookeeper.log
    source: zookeeper
    service: <SERVICE_NAME>
    log_processing_rules:
      - type: multi_line
        name: start_with_date
        pattern: \d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])" >/tmp/logs.config
sudo sed -i '/## Log Section/r /tmp/logs.config' /etc/datadog-agent/conf.d/zk.d/conf.yaml

# RESTARTING AGENT
sudo service datadog-agent-sysprobe start
sudo service datadog-agent restart
